[env]
RUST_BACKTRACE = "1"

[tasks.install-nightly]
script = '''
if [ -z "$(rustup toolchain list | grep 'nightly')" ];
then
  rustup toolchain install nightly
else
  echo "nightly is already installed."
fi
'''

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt"]
dependencies = ["install-nightly"]

[tasks.doctest]
command = "cargo"
args = ["--locked", "test", "--doc", "--", "--quiet"]

[tasks.test]
command = "cargo"
args = ["--locked", "test", "--tests", "--", "--quiet"]
dependencies = ["doctest"]

[tasks.tdd]
install_crate = "cargo-watch"
command = "cargo"
args = [ "watch"
       , "--watch", "./src"
       , "--watch", "./tests"
       , "--delay", "0"
       , "-x", "make -t test"
       ]

[tasks.check-fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--check"]
dependencies = ["install-nightly"]

[tasks.check-clippy]
command = "cargo"
args = ["clippy"]

[tasks.ci]
dependencies = ["test", "check-fmt", "check-clippy"]

[tasks.update-readme]
script = "cargo install cargo-readme && cargo readme > README.md"
